var myString;
var myNumber;
var myBoolean;
var myVariable;
var strArr;
var numArr;
var boolArr;
var varArr;
var strArrOther;
var numArrOther;
var boolArrOther;
var anyArrOther;
var strNumTuple;
myString = "Hello".slice(0, 3);
myNumber = 1;
myBoolean = false;
myVariable = true;
strArrOther = ["Hello", "World"];
numArr = [1, 2, 3];
boolArr = [true, false, true];
strNumTuple = ['Hello', 4];
var myVoid = undefined;
var myNull = null;
var myUndefined = null;
